/**
 * 12-row production method registry.
 * Mechanized verbatim from the #1165 frozen shape (rev11).
 *
 * Every row carries machine-readable metadata:
 *   - method name, direction, grant requirement
 *   - notification flag (only row 10)
 *   - ready status (only rows 1–2 true in beta.8)
 *   - leaf closure status and which matrix entries cause reservation
 *   - settlement key source
 *
 * A row may be marked `ready` only when its matrix entries all reach
 * CLOSED + generated byte proofs + N/N+1 conformance pass.
 * This module defines nothing new.
 *
 * ## Reserved matrix entry in-flight coordinates
 *
 * M7 — future-write admission half in review at clowder-ai#1185
 *      (exact 05ad80c6, gate PASS, Fable APPROVE current HEAD);
 *      stored-data attestation/migration half outstanding.
 *      Affects rows 6, 8, 9. M7 remains RESERVED.
 */

import type { Capability } from '../generated/contract.generated.js';
import { HANDSHAKE_ROW_ENCODED_BYTE_BOUNDS } from './handshake-byte-bounds.js';

// ---------------------------------------------------------------------------
// Direction + Grant types
// ---------------------------------------------------------------------------

/** Message direction on the wire. */
export type MethodDirection = 'plugin-to-host' | 'host-to-plugin';

/** Grant required to invoke a method, or protocol-intrinsic for handshake/lifecycle. */
export type GrantRequirement = Capability | 'protocol-intrinsic';

/** Leaf closure status from the variable-width leaf matrix. */
export type LeafClosureStatus = 'CLOSED' | 'RESERVED';

/** A schema field that must exist before or with a method's leaf closure. */
export interface SchemaClosurePrerequisite {
  readonly schemaPath: string;
  readonly timing: 'before-or-with-closure';
}

// ---------------------------------------------------------------------------
// Registry row shape
// ---------------------------------------------------------------------------

/**
 * A single row of the production method registry.
 * Most rows remain unpublished and unadvertised. beta.8 closes and exposes
 * only the two handshake rows.
 */
export interface RegistryRow {
  readonly rowNumber: number;
  readonly method: string;
  readonly direction: MethodDirection;
  readonly grant: GrantRequirement;
  readonly isNotification: boolean;
  readonly ready: boolean;
  readonly leafClosure: LeafClosureStatus;
  readonly reservedEntries: readonly string[];
  readonly settlementKeySource: string;
  /** Derived compact-frame maxima, present only for rows with closed wire shapes. */
  readonly maxEncodedRequestBytes?: number;
  readonly maxEncodedResultBytes?: number;
  readonly maxEncodedErrorBytes?: number;
  /** Schema fields required before this row may change from RESERVED to CLOSED. */
  readonly schemaClosurePrerequisites?: readonly SchemaClosurePrerequisite[];
}

/** A registry row whose input is publicly ready for dispatch. */
export interface ReadyRegistryRow extends RegistryRow {
  readonly ready: true;
}

/** A registry row that remains unready, whether its leaves are CLOSED or RESERVED. */
export interface UnreadyRegistryRow extends RegistryRow {
  readonly ready: false;
}

// ---------------------------------------------------------------------------
// Method name enum
// ---------------------------------------------------------------------------

/**
 * The exact 12 production method names, in registry order.
 * No production method exists for fixture setup/observe, grant presets,
 * revocation, permission-matrix inspection, or replay deletion.
 */
export const WIRE_METHOD_NAMES = [
  'broker.hello',
  'broker.ready',
  'messaging.send',
  'messaging.appendElements',
  'messaging.subscribe',
  'messaging.read',
  'messaging.ack',
  'messaging.snapshot',
  'host.messaging.deliver',
  'host.grants.changed',
  'host.lifecycle.ping',
  'host.lifecycle.drain',
] as const;

/** Union of all 12 production method names. */
export type WireMethodName = (typeof WIRE_METHOD_NAMES)[number];

/**
 * Literal readiness partition. This prevents a registry edit from widening a
 * newly closed row back to `boolean` or accidentally advertising another row.
 */
export type WireMethodRegistry = {
  readonly [Method in WireMethodName]: Method extends 'broker.hello' | 'broker.ready'
    ? ReadyRegistryRow
    : UnreadyRegistryRow;
};

// ---------------------------------------------------------------------------
// The complete registry (frozen)
// ---------------------------------------------------------------------------

/**
 * Machine-readable registry of all 12 production methods.
 *
 * Every value traces to the #1165 frozen shape. Row metadata includes
 * the exact matrix entry IDs that block leaf closure. Settlement key
 * sources follow the canonical per-row specification.
 *
 * Rows 1–2 are ready after beta.8's closure; rows 3–12 remain false.
 */
export const WIRE_METHOD_REGISTRY = {
  'broker.hello': {
    rowNumber: 1,
    method: 'broker.hello',
    direction: 'plugin-to-host',
    grant: 'protocol-intrinsic',
    isNotification: false,
    ready: true,
    leafClosure: 'CLOSED',
    reservedEntries: [],
    settlementKeySource: '—',
    ...HANDSHAKE_ROW_ENCODED_BYTE_BOUNDS['broker.hello'],
  },
  'broker.ready': {
    rowNumber: 2,
    method: 'broker.ready',
    direction: 'plugin-to-host',
    grant: 'protocol-intrinsic',
    isNotification: false,
    ready: true,
    leafClosure: 'CLOSED',
    reservedEntries: [],
    settlementKeySource: '—',
    ...HANDSHAKE_ROW_ENCODED_BYTE_BOUNDS['broker.ready'],
  },
  'messaging.send': {
    rowNumber: 3,
    method: 'messaging.send',
    direction: 'plugin-to-host',
    grant: 'messaging.send',
    isNotification: false,
    ready: false,
    leafClosure: 'RESERVED',
    reservedEntries: ['M1', 'M2', 'M5', 'I1'],
    settlementKeySource: 'input.idempotencyKey',
    // The receipt handle is publishable independently, but it is never a
    // substitute for closing this row's remaining M1/M2/M5/I1 obligations.
    schemaClosurePrerequisites: [
      { schemaPath: 'SendReceipt.handle', timing: 'before-or-with-closure' },
    ],
  },
  'messaging.appendElements': {
    rowNumber: 4,
    method: 'messaging.appendElements',
    direction: 'plugin-to-host',
    grant: 'messaging.appendElements',
    isNotification: false,
    ready: false,
    leafClosure: 'RESERVED',
    reservedEntries: ['M1', 'M2', 'M5', 'I1'],
    settlementKeySource: '(Host-resolved messageId from input.handle, input.operationId)',
  },
  'messaging.subscribe': {
    rowNumber: 5,
    method: 'messaging.subscribe',
    direction: 'plugin-to-host',
    grant: 'message.event.subscribe',
    isNotification: false,
    ready: false,
    leafClosure: 'CLOSED',
    reservedEntries: [],
    settlementKeySource: 'Host-resolved input.handle identity (K-1 create-or-get authoritative)',
  },
  'messaging.read': {
    rowNumber: 6,
    method: 'messaging.read',
    direction: 'plugin-to-host',
    grant: 'message.event.subscribe',
    isNotification: false,
    ready: false,
    leafClosure: 'RESERVED',
    reservedEntries: ['M1', 'M2', 'M5', 'M6', 'M7', 'I1'],
    settlementKeySource: 'none (at-least-once; bounded page assembly)',
  },
  'messaging.ack': {
    rowNumber: 7,
    method: 'messaging.ack',
    direction: 'plugin-to-host',
    grant: 'message.event.subscribe',
    isNotification: false,
    ready: false,
    leafClosure: 'CLOSED',
    reservedEntries: [],
    settlementKeySource: '(input.subscriptionId, input.ackToken)',
  },
  'messaging.snapshot': {
    rowNumber: 8,
    method: 'messaging.snapshot',
    direction: 'plugin-to-host',
    grant: 'message.event.subscribe',
    isNotification: false,
    ready: false,
    leafClosure: 'RESERVED',
    reservedEntries: ['M1', 'M2', 'M5', 'M7', 'I1'],
    settlementKeySource: 'none for traversal; completion = D1b Host entitlement through messaging.ack',
  },
  'host.messaging.deliver': {
    rowNumber: 9,
    method: 'host.messaging.deliver',
    direction: 'host-to-plugin',
    grant: 'onMessage',
    isNotification: false,
    ready: false,
    leafClosure: 'RESERVED',
    reservedEntries: ['M1', 'M2', 'M5', 'M7', 'I1'],
    settlementKeySource: 'input.deliveryId (Host-side authoritative)',
  },
  'host.grants.changed': {
    rowNumber: 10,
    method: 'host.grants.changed',
    direction: 'host-to-plugin',
    grant: 'protocol-intrinsic',
    isNotification: true,
    ready: false,
    leafClosure: 'CLOSED',
    reservedEntries: [],
    settlementKeySource: '(grantRevision monotonic)',
  },
  'host.lifecycle.ping': {
    rowNumber: 11,
    method: 'host.lifecycle.ping',
    direction: 'host-to-plugin',
    grant: 'protocol-intrinsic',
    isNotification: false,
    ready: false,
    leafClosure: 'CLOSED',
    reservedEntries: [],
    settlementKeySource: '—',
  },
  'host.lifecycle.drain': {
    rowNumber: 12,
    method: 'host.lifecycle.drain',
    direction: 'host-to-plugin',
    grant: 'protocol-intrinsic',
    isNotification: false,
    ready: false,
    leafClosure: 'CLOSED',
    reservedEntries: [],
    settlementKeySource: '—',
  },
} as const satisfies WireMethodRegistry;

// ---------------------------------------------------------------------------
// Derived helpers
// ---------------------------------------------------------------------------

/** Plugin-to-host method names. */
export const PLUGIN_TO_HOST_METHODS: readonly WireMethodName[] =
  WIRE_METHOD_NAMES.filter(m => WIRE_METHOD_REGISTRY[m].direction === 'plugin-to-host');

/** Host-to-plugin method names. */
export const HOST_TO_PLUGIN_METHODS: readonly WireMethodName[] =
  WIRE_METHOD_NAMES.filter(m => WIRE_METHOD_REGISTRY[m].direction === 'host-to-plugin');

/** Notification method names (only row 10 in v0). */
export const NOTIFICATION_METHODS: readonly WireMethodName[] =
  WIRE_METHOD_NAMES.filter(m => WIRE_METHOD_REGISTRY[m].isNotification);

/** Method names with CLOSED leaf shapes (frozen). */
export const CLOSED_LEAF_ROWS: readonly WireMethodName[] =
  WIRE_METHOD_NAMES.filter(m => WIRE_METHOD_REGISTRY[m].leafClosure === 'CLOSED');

/** Method names with RESERVED leaf shapes (may change). */
export const RESERVED_LEAF_ROWS: readonly WireMethodName[] =
  WIRE_METHOD_NAMES.filter(m => WIRE_METHOD_REGISTRY[m].leafClosure === 'RESERVED');

/** Method names that are legal for wire advertisement in beta.8. */
export const READY_ROWS: readonly WireMethodName[] =
  WIRE_METHOD_NAMES.filter(m => WIRE_METHOD_REGISTRY[m].ready);

/** Total number of production methods. */
export const WIRE_METHOD_COUNT = 12 as const;

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/**
 * Look up a registry row by method name.
 * Returns undefined for unknown method names.
 */
export function getRegistryRow(method: string): RegistryRow | undefined {
  return (WIRE_METHOD_REGISTRY as Record<string, RegistryRow>)[method];
}

/**
 * Check whether a method name is a valid wire method.
 */
export function isWireMethod(method: string): method is WireMethodName {
  return (WIRE_METHOD_NAMES as readonly string[]).includes(method);
}

/**
 * Get the grant requirement for a method.
 * Returns undefined for unknown method names.
 */
export function getMethodGrant(method: string): GrantRequirement | undefined {
  return getRegistryRow(method)?.grant;
}
